services:
  app:
    image: whitelokki/simple-service:${SERVICE_VERSION}
    build:
      context: ../
      dockerfile: Dockerfile
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
